version: 2.1
executors:
  lighthouse-executor:
    docker:
      - image: circleci/node:10.16-browsers

jobs:
  lhci_report:
    executor: lighthouse-executor
    steps:
      - run:
          name: pre build
          command: |
            npm install
            npm run build
      - run:
          name: Install lhci
          command: |
            sudo npm install -g @lhci/cli
      - run:
          name: Check lhci
          command: |
            lhci --version
      - run:
          name: Health Check
          command: |
            lhci healthcheck
      - run:
          name: Run lici (mannual)
          command: |
            lhci collect
            lhci assert
            lhci upload --target==temporary-public-storage
            ls -la .
      - run:
          name: Run lhci (autorun)
          command: |
            lhci autorun --upload.target=temporary-public-storage
            ls -la .
      - store_artifacts:
          path: '.'
      - run:
          name: Notify to slack
          command: | # XXXXXXXXはプロジェクトID
              echo "payload={'channel': '#development_info', 'username': 'test-webhook', 'text': ':circleci: lighthouse report: <https://${CIRCLE_BUILD_NUM}-XXXXXXXX-gh.circle-artifacts.com/0${HOME}/project/myfile.report.html|open report ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} > (build ${CIRCLE_BUILD_NUM})' }"

  lighthouse_report:
    executor: lighthouse-executor
    steps:
      - run:
          name: Install lighthouse
          command: |
            sudo npm install -g lighthouse
      - run:
          name: Check lighthouse
          command: |
            lighthouse --version
      - run:
          name: Run lighthouse
          command: |
            lighthouse https://wp-kyoto.net/ --output html --output json --output-path ./myfile.json
      - store_artifacts:
          path: '.'
      - run:
          name: Notify to slack
          command: | # XXXXXXXXはプロジェクトID
              echo "payload={'channel': '#development_info', 'username': 'test-webhook', 'text': ':circleci: lighthouse report: <https://${CIRCLE_BUILD_NUM}-XXXXXXXX-gh.circle-artifacts.com/0${HOME}/project/myfile.report.html|open report ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} > (build ${CIRCLE_BUILD_NUM})' }"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lhci_report
      - lighthouse_report